'service cgred start' should print some meaningful error message when there are no cgroups on the system.
Before:
	Starting CGroup Rules Engine Daemon:              [FAILED]
After:
	Starting CGroup Rules Engine Daemon:
	Cannot find cgroups, is cgconfig service running? [FAILED]


Signed-off-by: Jan Safranek <jsafrane@redhat.com>
Acked-by: Dhaval Giani <dhaval.giani@gmail.com>

diff --git a/scripts/init.d/cgred.in b/scripts/init.d/cgred.in
--- a/scripts/init.d/cgred.in
+++ b/scripts/init.d/cgred.in
@@ -72,6 +72,11 @@ start()
 		log_failure_msg "not configured"
 		return 6
 	fi
+	if ! grep "^cgroup" /proc/mounts &>/dev/null; then
+		echo
+		log_failure_msg $"Cannot find cgroups, is cgconfig service running?"
+		return 1
+	fi
 	daemon --check $servicename --pidfile $pidfile $CGRED_BIN $OPTIONS
 	RETVAL=$?
 	echo
